type: AFD
states:
  - q0
  - q1
  - q2
  - q3
  - qf
alphabet:
  - a
  - b
start: q0
ends:
  - qf
rules:
  q0:
    a:
      - q1
    b:
      - q0
  q1:
    a:
      - q1
    b: 
      - q2
  q2:
    a:
      - q0
    b:
      - q3
  q3:
    a:
      - q1
    b:
      - qf
  qf:
    a:
      - qf
    b:
      - qf
