type: PILHA
states:
  - q0
  - q1
  - qf
alphabet:
  - a
  - b
start: q0
ends:
  - qf
rules:
  q0:
    - [a, vz, B, [q0]]
    - [b, B, vz, [q1]]
    - ['?', '?', vz, [qf]]
  q1:
    - [b, B, vz, [q1]]
    - ['?', '?', vz, [qf]]
