type: PILHA
states:
  - q0
  - q1
  - q2
  - qf
alphabet:
  - a
  - b
start: q0
ends:
  - qf
rules:
  q0:
    - [a, vz, X, [q0]]
    - [vz, vz, vz, [q1]]
  q1:
    - [b, vz, X, [q1]]
    - [vz, vz, vz, [q2]]
  q2:
    - [a, X, vz, [q2]]
    - ['?', '?', vz, [qf]]
