type: PILHA
states:
  - q0
  - q1
  - qf
alphabet:
  - a
  - b
start: q0
ends:
  - qf
rules:
  q0:
    - [a, vz, A, [q1]]
  q1:
    - [b, A, vz, [q1]]
    - [a, A, vz, [q0]]
    - [INTE, INTE, vz, [qf]]
